### ISSUE TITLE
forecast sales

### ISSUE THREAD

**Issue by ghost** [ninolina/couchbaseViews#1]
Im Key von Forecast Sales muss PLAN_PERIOD hinzugefügt werden. (NUR in forecast sales)

**Comment by ninolina** [comment]
Ist schon da bei Sales... 
"if(doc.TYPE == "FC_FORECAST_SALES"){
      emit([doc.PLAN_PERIOD,doc.PRODUCT_MAIN_GROUP, doc.REGION],..."  Vllt mal besser gucken... :D 
 Aber es ist auch beim Costs da - soll es da sein, oder doch nicht?

**Comment by ghost** [comment]
Sorry falsch gesehen.
Bitte folgende reihenfolge: pmg,region,period, plan_period

**Comment by ninolina** [comment]
Already done und schon am Server... :)

**Comment by ghost** [comment]
Vielen Dank
